export const TRPC_URL = '/trpc'

export const MIN_FAKE_POSTS = 0
export const MAX_FAKE_POSTS = 6

export const FAKE_POST_STRINGS = {
  holyShit: [
    'Bro',
    'I cannot believe it',
    'What the fuck',
    'Holy fuck',
    'Holy shit',
    'Not surprised',
    'Unsurprising',
    'Not cool',
    'Come on',
  ],
  thisShitIs: [
    'this shit is',
    'guys this is',
    'this post is',
    'this thing is',
    'that guy is',
    'that thing is',
    "it's",
    'it is',
    "it's all",
  ],
  so: [
    'so',
    'fucking',
    'so fucking',
    'freaking',
    'so freaking',
    'insanely',
    'ultra',
    'not',
  ],
  adjective: [
    'poggers',
    'awesome',
    'goated',
    'winning',
    'killer',
    'the tits',
    'epic',
    'unreal',
    'awesome',
    'shit',
    'cool',
    'neat',
    'dog',
    'dogshit',
    'ridiculous',
    'fake',
    'faked',
    'shitty',
    'stupid',
    'retarded',
    'autistic',
    'evil',
    'pretentious',
    'annoying',
    'cringe',
    'cap',
  ],
  hey: [
    'Hey',
    'Yo',
    'Ay',
    'Listen',
    'Listen here',
    'Hey',
    'Alright',
    'Ok',
    'Hey',
    'Hi',
    'Hello',
    'Yo',
  ],
  fuckYou: ['fuck you', 'die', 'eat shit', 'you suck', 'piss off'],
  dude: [
    'bro',
    'man',
    'dude',
    'guys',
    'chat',
    'buddy',
    'hoss',
    'friend',
    'fucker',
  ],
  thisIs: ['This is', 'Hi, this is', 'Hello. This is', 'This is the official'],
  cnn: [
    'CNN',
    'Fox News',
    'BBC',
    'NYT',
    'New York Times',
    'CBS',
    'NBC',
    'LA Times',
    'Shanghai Times',
    'Beijing Times',
  ],
  withNews: [
    'with breaking news',
    'with a new story',
    'and there is news',
    'with the newest stories',
  ],
  specificReply: [
    'Hi :)',
    'Who else up playing with they worm',
    'Who else up',
    'Hop on val',
    'Real (not fake)',
    'Real',
    "This can't be real",
    'Mind blown',
    'Determination',
    'I can has cheezburger?',
    'Donal trump be like',
    'Cats',
    'Dogs',
    'Guys',
    'Guys be like',
    'Dudes be like',
    'Girls be like',
    'Chicks be like',
    'White people be like',
    'Dumb fuck',
    'Fucking idiot',
  ],
  punctuation: ['.', '!', '...', '..?', '..!', ';', '.!'],
  subtitleIdiom: [
    'Do unto others as you would have done unto yourself',
    'Trust no one',
    "It didn't seem that bad at first",
    'You came all this way, but for what',
    "Life isn't fair sometimes",
    'The squeaky wheel gets the grease',
    'Yo mama so fat',
    'Just be realistic next time',
    "You don't always get what you wish for",
    'Be careful what you wish for',
    'An apple a day',
    "There's always a bigger fish",
  ],
  subtitleOneWord: [
    'Bro',
    'Awesome',
    'Sick',
    'Epic',
    'Sweet',
    'Nice',
    'Uncool',
    'Not nice',
    'Damn',
    'Fuck',
    'Bastard',
    'Hey',
  ],
  subtitleSpecific: [
    "I can't believe this is happening.",
    'Hi guys :)',
    'Hi :)',
    'What the h*ck... what the h*ck man...',
    "Don't mind and I do!",
    'Uhh... What?',
    'Excuse me?',
    'HELP!! HELP!!! HELP!!',
    "Well if it isn't you...",
  ],
}

export const FAKE_POST_PROBABILITIES = {
  isReply: 0.36,
  reply: {
    isReaction: 0.4,
    reaction: { holyShit: 0.4, thisIs: 0.8, so: 0.3, dude: 0.3 },

    isInsult: 0.4,
    insult: { hey: 0.7, dude1: 0.35, dude2: 0.8 },

    isSpecific: 1,
  },

  isNews: 0.4,
  news: { thisIs: 0.7, withNews: 0.5 },

  subtitle: {
    isSame: 0.55,
    same: {
      hasExtraBro: 0.4,
    },
    isSingleWord: 0.35,
    singleWord: {
      hasPunctuation: 0.5,
    },
    isIdiom: 0.5,
    isSpecific: 1,
  },

  hasTypo: 0.15,
  hasSubtitle: 0.85,
}
